### ISSUE TITLE
Catch all domains

### ISSUE THREAD

**Issue by zorahrel** [jwilder/nginx-proxy#910]
I am not able to run a Container within Docker Compose that catches all domains. I tried with
```
...
environment:
      - VIRTUAL_HOST=_
...
```
or
```
...
environment:
      - VIRTUAL_HOST=*
...
```
or removing VIRTUAL_HOST param

But nothing of above catches the domain, instead throws error `503 Service Temporarily Unavailable`.

Any idea?

**Comment by wader** [comment]
Should it be a regexp? try `.*` otherwise maybe `DEFAULT_HOST` can be used?

**Comment by zorahrel** [comment]
@wader Tried, not working

**Comment by wader** [comment]
Tried both? I think `DEFAULT_HOST` should solve it at least. Note that `DEFAULT_HOST` should be a environment variable on the nginx-proxy container.

**Comment by zorahrel** [comment]
Yes @wader. I tried with `DEFAULT_HOST=_` and `DEFAULT_HOST=.*` but still don't work.

I am testing like this:
`docker-compose.yml` file:
```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
  professional-site:
    image: betalab/professional-site
    container_name: professional-site
    environment:
      - DEFAULT_HOST=_
```

`my_proxy.conf` file:
```
server {
    server_name _;
	listen 80 default_server;
	return 500;
}
```

It throws me error 500 when line
`- /root/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro` is there, instead 503 when I remove it.

**Comment by wader** [comment]
Ah ok, `DEFAULT_HOST` should be a hostname used by some other container

**Comment by zorahrel** [comment]
@wader You mean that something is using the hostname?

**Comment by wader** [comment]
I mean that `DEFAULT_HOST` should be set to some hostname used in a `VIRTUAL_HOST`

**Comment by zorahrel** [comment]
@wader thank you!
works like this:
```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=_
  professional-site:
    image: betalab/professional-site
    container_name: professional-site
    environment:
      - VIRTUAL_HOST=_
```

**Comment by wader** [comment]
Nice!

**Comment by kfkonrad** [comment]
I had the same issue, the DEFAULT_HOST behaviour isn't well documented. I fixed that in pull request #1145
